#!/bin/bash

if command -v iwctl > /dev/null
then
    # Method 1. Ask the interface to scan again
    # TODO: dynamically get the <interface>
    INTERFACE="wlan0"
    printf "iwctl station \"$INTERFACE\" connect \"$@\"\n"
    iwctl station "$INTERFACE" connect "$1"
elif command -v nmcli > /dev/null
then
    nmcli radio wifi on
fi
